backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
public_folder: "/images"
collections:
- label: "Pages"
  name: "pages"
  files:
    - label: "Home Page"
      name: "home"
      file: "content/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Paragrap Title, name: paragrap_title, widget: string, required: false}
        - {label: Paragrap Link, name: paragrap_link, widget: string, required: false}
        - {label: Content, name: body, widget: markdown, required: false}
        - {label: Google Map Coordinates, name: google_map_coordinates, widget: string}
        - {label: Business Name, name: business_name, widget: string, required: false}
        - {label: Address, name: address, widget: text, required: false}
        - {label: Telephone No, name: phone, widget: string, required: false}
        - {label: Phone No, name: mobile, widget: string, required: false}
        - {label: Email, name: email, widget: string, required: false}
        - label: Slides
          name: slides
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
- label: "Data"
  name: "data"
  files:
    - label: "Bathroom Partner Brands"
      name: "bathroom"
      file: "data/bathroom.yml"
      fields:
        - label: Bathroom Partner Brands
          name: bathroom
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
    - label: "Kitchen Partner Brands"
      name: "kitchen"
      file: "data/kitchen.yml"
      fields:
        - label: Kitchen Partner Brands
          name: kitchen
          widget: list
          fields:
            - {label: Image, name: image, widget: image}

    - label: "Meta"
      name: "meta"
      file: "data/meta.yml"
      fields:
        - {label: Page Background, name: background_image, widget: image, required: false}
        - {label: Logo, name: logo, widget: image, required: false}
        - {label: FB Cover, name: fb_cover, widget: image, required: false}
        - {label: Header Color, name: header_color, widget: text, required: false}
        - {label: Footer Color, name: footer_color, widget: text, required: false}
