backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
public_folder: "/images"
collections:
- label: "Agriculture"
  name: "agriculture"
  folder: "content/agriculture"
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Featured Image, name: featured_image, widget: image, required: false}
    - {label: Content, name: body, widget: markdown, required: false}
    - label: "Type"
      name: "type"
      widget: "select"
      options: ["agriculture", "crop_advisory","two_column_template", "three_column_template", "three_grid_template"]
    - label: Header
      name: header
      widget: list
      fields:
        - {label: Header Title, name: header_title, widget: string, required: false}
    - label: Details
      name: details
      widget: list
      fields:
        - {label: Name, name: name, widget: string, required: false}
        - {label: Image, name: image, widget: image, required: false}
        - {label: Profile File, name: profile_file, widget: file, required: false}
        - {label: Action, name: action, widget: text, required: false}
- label: "About"
  name: "about"
  folder: "content/about"
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Featured Image, name: featured_image, widget: image, required: false}
    - {label: Content, name: body, widget: markdown, required: false}
- label: "Bio Cleaners"
  name: "bio cleaners"
  folder: "content/bio_cleaners"
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Featured Image, name: featured_image, widget: image, required: false}
    - {label: Content Header, name: content_header, widget: text, required: false}
    - {label: Content, name: body, widget: markdown, required: false}
    - {label: Table Header, name: table_header, widget: text, required: false}
    - label: Formulations
      name: formulations
      widget: list
      fields:
        - {label: Name, name: name, widget: text, required: false}
- label: "Contact Page"
  name: "contact"
  folder: "content/contact"
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Google Map Coordinates, name: google_map_coordinates, widget: string, required: false}
    - {label: Business Name, name: business_name, widget: string, required: false}
    - {label: Address, name: address, widget: text, required: false}
    - {label: Phone No, name: mobile, widget: string, required: false}
    - {label: Email, name: email, widget: string, required: false}

- label: "Pages"
  name: "pages"
  files:
    - label: "Home Page"
      name: "home"
      file: "content/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Paragrap Title, name: paragrap_title, widget: string, required: false}
        - {label: Paragrap Link, name: paragrap_link, widget: string, required: false}
        - {label: Content, name: body, widget: markdown, required: false}
        - {label: Product Title, name: product_title, widget: string, required: false}
        - label: Slides
          name: slides
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
- label: "Data"
  name: "data"
  files:
    - label: "Services"
      name: "services"
      file: "data/services.yml"
      fields:
        - label: Services
          name: services
          widget: list
          fields:
            - {label: Name, name: name, widget: string, required: false}
            - {label: Image, name: image, widget: image, required: false}
            - {label: Content, name: content, widget: markdown, required: false}
            - {label: Link, name: link, widget: string, required: false}

    - label: "Meta"
      name: "meta"
      file: "data/meta.yml"
      fields:
        - {label: Page Background, name: background_image, widget: image, required: false}
        - {label: Logo, name: logo, widget: image, required: false}
        - {label: FB Cover, name: fb_cover, widget: image, required: false}
        - {label: Header Color, name: header_color, widget: text, required: false}
        - {label: Footer Color, name: footer_color, widget: text, required: false}
